name: Secret Scanning with TruffleHog

on:
  pull_request:
    branches:
      - main  # Change this to match your default branch

jobs:
  secret-scan:
    name: Scan PR for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we get full history for diff scanning

      - name: Install TruffleHog
        run: |
          pip install trufflehog
          trufflehog --version  # Check installed version

      - name: Get Changed Files
        id: changed-files
        run: |
          git fetch origin main
          git diff --name-only origin/main > changed_files.txt
          cat changed_files.txt

      - name: Run TruffleHog on Changed Files
        run: |
          while IFS= read -r file; do
            echo "Scanning $file"
            trufflehog filesystem --path "$file" --json | tee -a trufflehog_results.json || true
          done < changed_files.txt

      - name: Fail if secrets are detected
        run: |
          if [ -s trufflehog_results.json ]; then
            echo "Secrets detected!"
            cat trufflehog_results.json
            exit 1
          else
            echo "No secrets found."
          fi
