name: Secret Scanning with TruffleHog

on:
  pull_request:
    branches:
      - main  # Change this to match your default branch

jobs:
  secret-scan:
    name: Scan PR for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for diff scanning

      - name: Install TruffleHog
        run: |
          pip install trufflehog

      - name: Run TruffleHog on Changed Files
        run: |
          git diff --name-only origin/main > changed_files.txt
          if [ -s changed_files.txt ]; then
            trufflehog filesystem --pathlist changed_files.txt --json > trufflehog_results.json || true
          else
            echo "No changed files detected."
          fi

      - name: Fail if secrets are detected
        run: |
          if [ -s trufflehog_results.json ]; then
            echo "Secrets detected!"
            cat trufflehog_results.json
            exit 1
          else
            echo "No secrets found."
          fi
