name: Secret Scanning with TruffleHog

on:
  pull_request:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  secret-scan:
    name: Scan PR for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Run TruffleHog Secret Scan using Docker
        run: |
          # Run the latest TruffleHog Docker image.
          # This scans the entire repository (by Git URL).
          docker run --rm trufflesecurity/trufflehog:latest --regex --entropy=True https://github.com/${{ github.repository }} | tee trufflehog_output.txt
          
          # If output contains the word "Reason", assume a secret was found.
          if grep -q "Reason" trufflehog_output.txt; then
            echo "🚨 Secrets detected by TruffleHog!"
            exit 1
          else
            echo "✅ No secrets detected."
          fi
