name: Secret Scanning with TruffleHog

on:
  pull_request:
    branches:
      - main  # Ensure it runs on PRs to main

jobs:
  secret-scan:
    name: Scan PR for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we can diff against main

      - name: Install TruffleHog
        run: |
          pip install trufflehog
          trufflehog --version  # Confirm installation

      - name: Get Changed Files
        id: changed-files
        run: |
          git diff --name-only origin/main > changed_files.txt
          cat changed_files.txt

      - name: Run TruffleHog on Changed Files
        run: |
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              echo "Scanning $file"
              trufflehog --regex --entropy=True "$file" | tee -a trufflehog_results.json || true
            else
              echo "Skipping $file (not a regular file)"
            fi
          done < changed_files.txt

      - name: Fail if secrets are detected
        run: |
          if grep -q "Reason" trufflehog_results.json; then
            echo "🚨 Secrets detected in changed files!"
            exit 1
          else
            echo "✅ No secrets found in changed files."
          fi
